### ISSUE TITLE
PHPUnit extension registered twice

### ISSUE THREAD

**Issue by ondrejmirtes** [WyriHaximus/php-phpstan-rules-wrapper#1]
You have registered phpstan-phpunit/extension.neon twice - it would certainly crash on startup 😊

**Comment by WyriHaximus** [comment]
Included rules and extension, not extension twice unless I missed something :sunglasses:

**Comment by ondrejmirtes** [comment]
The first and last line of the file is the same and it’s extension.neon 😊

**Comment by WyriHaximus** [comment]
Doh you're right, was only looking at the last two lines :blush: . Fixed it now, thanks for the heads up :+1:
